### ISSUE TITLE
CPAN version breaks with mojolicious 6.

### ISSUE THREAD

**Issue by cfedde** [abhishekisnot/Mojolicious-Plugin-REST#8]
It appears that the HEAD here passes but the revision in CPAN breaks with the most recent Mojolicious.

```
t/01_basic.t ......... ok
Can't locate object method "bridge" via package "Mojolicious::Routes" at /home/cfedde/.cpanm/work/1431031363.7726/Mojolicious-Plugin-REST-0.006/blib/lib/Mojolicious/Plugin/REST.pm line 114.
t/02_associations.t .. 
Dubious, test returned 2 (wstat 512, 0x200)
No subtests run 
```

**Comment by omani** [comment]
can you tell when you will fix this?

**Comment by biancalana** [comment]
any news on this ?

**Comment by jjehannet** [comment]
You could try patching the file Plugin/REST.pm (twice) as follows :

```
 = $routes->bridge($url)->to(...
```

by

```
 = $routes->under($url)->to(...
```

From Plugin/REST.pm documentation:

In Mojolicious version 5.X, the actual bridge code needs to return a true value or the dispatch chain will be broken.
Since Mojolicious 6.0 removed the method bridge, you should use under prefered - indeed, the bridge method has been marked deprecated since Mojolicious 5.73.

See also http://mojolicio.us/perldoc/Mojolicious/Guides/Routing#Under
